/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package amazonsearchautomation;

import java.net.MalformedURLException;
import java.time.Duration;

import org.openqa.selenium.firefox.FirefoxDriver;

import io.github.bonigarcia.wdm.WebDriverManager;

public class App {
   static FirefoxDriver driver;
    public FirefoxDriver creatFirefoxDriver()
    {
        System.out.println("Constructor: TestCases");
        WebDriverManager.chromedriver().timeout(30).setup();
        driver = new FirefoxDriver();
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(30));
        return driver;

    }
    public void getGreeting(FirefoxDriver driver2) throws InterruptedException, MalformedURLException {
        FirefoxDriver driver3 = driver2;
        TestCases tests = new TestCases(); // Initialize your test class

        
        tests.testCase01(driver3);

        //END Tests


        tests.endTest(driver3); // End your test by clearning connections and closing browser
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        App app = new App();
        FirefoxDriver driver = app.creatFirefoxDriver();
        new App().getGreeting(driver);
    }

}
